### ISSUE TITLE
Toolbar: Opening an extension popup exits fullscreen

### ISSUE THREAD

**Issue by powellnorma** [samuelmaddock/electron-browser-shell#148]
Is there an option to disable this behavior?

**Comment by samuelmaddock** [comment]
Which electron and OS versions?

**Comment by powellnorma** [comment]
electron@35.0.0-beta.12, arch i3 4.24

https://github.com/samuelmaddock/electron-browser-shell/blob/3ed5c698d71d9c92fda00544730a0981c13cce36/packages/electron-chrome-extensions/src/browser/popup.ts#L58C30-L58C43

I am trying to use WebContentsView now instead of BrowserWindow, it seems to work better (does not exit fullscreen when opened) - Is there a gotcha with this though?

**Comment by samuelmaddock** [comment]
Fixed in electron-chrome-extensions@4.9.0

**Comment by powellnorma** [comment]
@samuelmaddock I just tested master, it's not fixed for me yet
